name: Handle stale issues
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  handle-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 28
          exempt-issue-labels: bug, enhancement
          stale-issue-message: >-
            There hasn’t been any activity here for four weeks. If no activity occurs over the next
            week, this issue will be closed as stale.
