name: Run tests
on:
  push:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 17
          distribution: adopt
      - run: |
          chmod +x gradlew
          ./gradlew test
